{"uid":"41d046d3acc0dba5","name":"Создание проекта с пустым названием","fullName":"tests.test_backend.project.test_project#test_project_name_empty","historyId":"fb497443fece2a3ff628735376d0f59b","time":{"start":1749799109119,"stop":1749799109544,"duration":425},"status":"passed","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_verify_url","time":{"start":1749799082902,"stop":1749799082902,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"owner_client","time":{"start":1749799082902,"stop":1749799083439,"duration":537},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"pytestconfig","time":{"start":1749799082902,"stop":1749799082902,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"delete_output_dir","time":{"start":1749799082902,"stop":1749799082902,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"base_url","time":{"start":1749799082902,"stop":1749799082902,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"temp_space","time":{"start":1749799083440,"stop":1749799084269,"duration":829},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"testStage":{"status":"passed","steps":[{"name":"Отправка запроса с пустым названием проекта","time":{"start":1749799109119,"stop":1749799109544,"duration":425},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"Проверка, что API вернул 404 – ошибка валидации","time":{"start":1749799109544,"stop":1749799109544,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":2,"attachmentsCount":0,"hasContent":true},"afterStages":[{"name":"temp_space::0","time":{"start":1749799117946,"stop":1749799118595,"duration":649},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"labels":[{"name":"tag","value":"backend"},{"name":"parentSuite","value":"tests.test_backend.project"},{"name":"suite","value":"test_project"},{"name":"host","value":"pkrvmxyh4eaekms"},{"name":"thread","value":"2539-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_backend.project.test_project"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"history":{"statistic":{"failed":0,"broken":8,"skipped":0,"passed":7,"unknown":0,"total":15},"items":[{"uid":"5736e52a3950902c","reportUrl":"https://vaizcom.github.io/autotests/129//#testresult/5736e52a3950902c","status":"passed","time":{"start":1749798770185,"stop":1749798770376,"duration":191}},{"uid":"398bd821571a71a2","reportUrl":"https://vaizcom.github.io/autotests/128//#testresult/398bd821571a71a2","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f254b41e350>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749798179035,"stop":1749798179035,"duration":0}},{"uid":"e6a675ad2f2850e","reportUrl":"https://vaizcom.github.io/autotests/127//#testresult/e6a675ad2f2850e","status":"passed","time":{"start":1749797916823,"stop":1749797917008,"duration":185}},{"uid":"3269713fca34129d","reportUrl":"https://vaizcom.github.io/autotests/126//#testresult/3269713fca34129d","status":"passed","time":{"start":1749745028598,"stop":1749745028812,"duration":214}},{"uid":"fa8fa3b57c02fa3e","reportUrl":"https://vaizcom.github.io/autotests/125//#testresult/fa8fa3b57c02fa3e","status":"passed","time":{"start":1749744429405,"stop":1749744429687,"duration":282}},{"uid":"dcf4d76a8321845a","reportUrl":"https://vaizcom.github.io/autotests/124//#testresult/dcf4d76a8321845a","status":"passed","time":{"start":1749744341036,"stop":1749744341241,"duration":205}},{"uid":"63cb311ad557f092","reportUrl":"https://vaizcom.github.io/autotests/123//#testresult/63cb311ad557f092","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f6ed7455e50>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749744006578,"stop":1749744006578,"duration":0}},{"uid":"afa1753f4b441619","reportUrl":"https://vaizcom.github.io/autotests/122//#testresult/afa1753f4b441619","status":"passed","time":{"start":1749743643977,"stop":1749743644240,"duration":263}},{"uid":"aa34859fb3b8c0ef","reportUrl":"https://vaizcom.github.io/autotests/119//#testresult/aa34859fb3b8c0ef","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc7b5913490>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749742823613,"stop":1749742823613,"duration":0}},{"uid":"4e2fc04181b99261","reportUrl":"https://vaizcom.github.io/autotests/118//#testresult/4e2fc04181b99261","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f9cb88f1f10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749742671136,"stop":1749742671136,"duration":0}},{"uid":"89daf65c8f0b3eaa","reportUrl":"https://vaizcom.github.io/autotests/117//#testresult/89daf65c8f0b3eaa","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2b9f21f250>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749742500892,"stop":1749742500892,"duration":0}},{"uid":"220505766cd3be5b","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/220505766cd3be5b","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741237247,"stop":1749741237247,"duration":0}},{"uid":"7fb68d6b5bfe9579","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/7fb68d6b5bfe9579","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740829928,"stop":1749740829928,"duration":0}},{"uid":"328b753a9e88a851","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/328b753a9e88a851","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740656525,"stop":1749740656525,"duration":0}}]},"tags":["backend"]},"source":"41d046d3acc0dba5.json","parameterValues":[]}