{"uid":"e49c0d362dbbf5d6","name":"Создание проекта с пустым описанием","fullName":"tests.test_backend.project.test_project#test_project_description_empty","historyId":"d2d6b127421e881191e1b41c382cd2a9","time":{"start":1749745029099,"stop":1749745029392,"duration":293},"status":"passed","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"owner_client","time":{"start":1749745001258,"stop":1749745001837,"duration":579},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"base_url","time":{"start":1749745001258,"stop":1749745001258,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"_verify_url","time":{"start":1749745001258,"stop":1749745001258,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"delete_output_dir","time":{"start":1749745001258,"stop":1749745001258,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"pytestconfig","time":{"start":1749745001258,"stop":1749745001258,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"temp_space","time":{"start":1749745001837,"stop":1749745002658,"duration":821},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"testStage":{"status":"passed","steps":[{"name":"Отправка запроса с пустым описанием проекта","time":{"start":1749745029099,"stop":1749745029392,"duration":293},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"Проверка, что API вернул 200 – описание не является обязательным к заполнению","time":{"start":1749745029392,"stop":1749745029392,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":2,"attachmentsCount":0,"hasContent":true},"afterStages":[{"name":"temp_space::0","time":{"start":1749745036075,"stop":1749745036872,"duration":797},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"labels":[{"name":"tag","value":"backend"},{"name":"parentSuite","value":"tests.test_backend.project"},{"name":"suite","value":"test_project"},{"name":"host","value":"pkrvmxyh4eaekms"},{"name":"thread","value":"2532-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_backend.project.test_project"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"history":{"statistic":{"failed":0,"broken":7,"skipped":0,"passed":4,"unknown":0,"total":11},"items":[{"uid":"c4363fbe0fb6fb1e","reportUrl":"https://vaizcom.github.io/autotests/125//#testresult/c4363fbe0fb6fb1e","status":"passed","time":{"start":1749744429951,"stop":1749744430273,"duration":322}},{"uid":"a443994fdabb7868","reportUrl":"https://vaizcom.github.io/autotests/124//#testresult/a443994fdabb7868","status":"passed","time":{"start":1749744341449,"stop":1749744341716,"duration":267}},{"uid":"e99298adb052b5a4","reportUrl":"https://vaizcom.github.io/autotests/123//#testresult/e99298adb052b5a4","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f6ed7455e50>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749744006726,"stop":1749744006726,"duration":0}},{"uid":"ffe5c61e76fac530","reportUrl":"https://vaizcom.github.io/autotests/122//#testresult/ffe5c61e76fac530","status":"passed","time":{"start":1749743644435,"stop":1749743644692,"duration":257}},{"uid":"8913afdd19f698a5","reportUrl":"https://vaizcom.github.io/autotests/119//#testresult/8913afdd19f698a5","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc7b5913490>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749742823762,"stop":1749742823762,"duration":0}},{"uid":"76a2d3aa04eee816","reportUrl":"https://vaizcom.github.io/autotests/118//#testresult/76a2d3aa04eee816","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f9cb88f1f10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749742671296,"stop":1749742671296,"duration":0}},{"uid":"a2e8bd3a2aa824eb","reportUrl":"https://vaizcom.github.io/autotests/117//#testresult/a2e8bd3a2aa824eb","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2b9f21f250>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749742501043,"stop":1749742501043,"duration":0}},{"uid":"a10501ad469f3ca5","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/a10501ad469f3ca5","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741237397,"stop":1749741237397,"duration":0}},{"uid":"4152b233b15d1fcb","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/4152b233b15d1fcb","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740830084,"stop":1749740830084,"duration":0}},{"uid":"a0bbdea8f28a7caa","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/a0bbdea8f28a7caa","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740656674,"stop":1749740656674,"duration":0}}]},"tags":["backend"]},"source":"e49c0d362dbbf5d6.json","parameterValues":[]}