{"uid":"685c5009ccf0ceea","name":"Валидация: создание борды с именем — ожидаемый статус 400","fullName":"tests.test_backend.board.board_validation_test#test_create_board_name_validation","historyId":"79e825556c8e979fb839ef559890d9cb","time":{"start":1749798747128,"stop":1749798747377,"duration":249},"status":"passed","flaky":false,"newFailed":false,"newBroken":false,"newPassed":true,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"delete_output_dir","time":{"start":1749798742635,"stop":1749798742635,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"owner_client","time":{"start":1749798742635,"stop":1749798743126,"duration":491},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"base_url","time":{"start":1749798742635,"stop":1749798742635,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"pytestconfig","time":{"start":1749798742635,"stop":1749798742635,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"_verify_url","time":{"start":1749798742635,"stop":1749798742635,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"temp_space","time":{"start":1749798743126,"stop":1749798744123,"duration":997},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"temp_project","time":{"start":1749798744123,"stop":1749798745984,"duration":1861},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"testStage":{"status":"passed","steps":[{"name":"Проверка, что API вернул статус 400 при none","time":{"start":1749798747377,"stop":1749798747377,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"attachments":[{"uid":"67a3e08dd0945852","name":"stdout","source":"67a3e08dd0945852.txt","type":"text/plain","size":71}],"parameters":[],"shouldDisplayMessage":false,"stepsCount":1,"attachmentsCount":1,"hasContent":true},"afterStages":[{"name":"temp_space::0","time":{"start":1749798778176,"stop":1749798778980,"duration":804},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"labels":[{"name":"tag","value":"backend"},{"name":"parentSuite","value":"tests.test_backend.board"},{"name":"suite","value":"board_validation_test"},{"name":"host","value":"pkrvmxyh4eaekms"},{"name":"thread","value":"2537-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_backend.board.board_validation_test"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"expected_status","value":"400"},{"name":"name","value":"None"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"history":{"statistic":{"failed":0,"broken":8,"skipped":0,"passed":6,"unknown":0,"total":14},"items":[{"uid":"45b5881cb83a3ff9","reportUrl":"https://vaizcom.github.io/autotests/128//#testresult/45b5881cb83a3ff9","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f254b41e350>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749798174866,"stop":1749798174866,"duration":0}},{"uid":"b169a8b9994befb1","reportUrl":"https://vaizcom.github.io/autotests/127//#testresult/b169a8b9994befb1","status":"passed","time":{"start":1749797895230,"stop":1749797895450,"duration":220}},{"uid":"63d233bd40338ae4","reportUrl":"https://vaizcom.github.io/autotests/126//#testresult/63d233bd40338ae4","status":"passed","time":{"start":1749745005724,"stop":1749745005957,"duration":233}},{"uid":"51990225bd97b2a9","reportUrl":"https://vaizcom.github.io/autotests/125//#testresult/51990225bd97b2a9","status":"passed","time":{"start":1749744403345,"stop":1749744403679,"duration":334}},{"uid":"ca754d9884e8198d","reportUrl":"https://vaizcom.github.io/autotests/124//#testresult/ca754d9884e8198d","status":"passed","time":{"start":1749744317528,"stop":1749744317926,"duration":398}},{"uid":"84b274f944015c77","reportUrl":"https://vaizcom.github.io/autotests/123//#testresult/84b274f944015c77","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f6ed7455e50>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749744002522,"stop":1749744002522,"duration":0}},{"uid":"b17c67e0eb8cdb32","reportUrl":"https://vaizcom.github.io/autotests/122//#testresult/b17c67e0eb8cdb32","status":"passed","time":{"start":1749743621034,"stop":1749743621468,"duration":434}},{"uid":"eaad7dee95aebea1","reportUrl":"https://vaizcom.github.io/autotests/119//#testresult/eaad7dee95aebea1","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc7b5913490>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749742819672,"stop":1749742819672,"duration":0}},{"uid":"4a6abca04037463d","reportUrl":"https://vaizcom.github.io/autotests/118//#testresult/4a6abca04037463d","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f9cb88f1f10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749742667037,"stop":1749742667037,"duration":0}},{"uid":"fecbf053a7ba2918","reportUrl":"https://vaizcom.github.io/autotests/117//#testresult/fecbf053a7ba2918","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2b9f21f250>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749742496802,"stop":1749742496802,"duration":0}},{"uid":"de51bbe4cd46760e","reportUrl":"https://vaizcom.github.io/autotests/116//#testresult/de51bbe4cd46760e","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7efcc7f78ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749741233265,"stop":1749741233265,"duration":0}},{"uid":"ce81737bf595c70f","reportUrl":"https://vaizcom.github.io/autotests/115//#testresult/ce81737bf595c70f","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f28d1ddcd10>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740825720,"stop":1749740825720,"duration":0}},{"uid":"8175a3373a3849e8","reportUrl":"https://vaizcom.github.io/autotests/114//#testresult/8175a3373a3849e8","status":"broken","statusDetails":"requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.vaiz.dev', port=443): Max retries exceeded with url: /v4/Login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f271b110ad0>, 'Connection to api.vaiz.dev timed out. (connect timeout=None)'))","time":{"start":1749740652501,"stop":1749740652501,"duration":0}}]},"tags":["backend"]},"source":"685c5009ccf0ceea.json","parameterValues":["400","None"]}